services:

  postgres_service:
    container_name: ultralytics_database
    image: postgres:16
    hostname: postgres_service
    ports:
      - "5441:5432"
    volumes:
      - ultralytics_database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ultralytics_database
      TZ: Asia/Tashkent
    networks:
      - ultralytics_network

networks:
  ultralytics_network:
    external: true

volumes:
  ultralytics_database_volume: