services:

  postgres_service:
    container_name: ultralytics_database
    image: postgres:16
    hostname: postgres_service
    ports:
      - "5441:5432"
    volumes:
      - ultralytics_database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ultralytics_database
      TZ: Asia/Tashkent
    networks:
      - ultralytics_network
  
  minio:
    container_name: ultralytics_minio
    image: minio/minio
    hostname: minio
    ports:
      - '9008:9000'
      - '9098:9090'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ultralytics_minio_data:/data
    networks:
      - ultralytics_network
    command: server /data --console-address ":9090"
networks:
  ultralytics_network:
    external: true

volumes:
  ultralytics_database_volume:
  ultralytics_minio_data: 