"""meal changes

Revision ID: 52d5f5a412b5
Revises: 99e403f1531f
Create Date: 2024-11-09 21:21:19.534481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52d5f5a412b5'
down_revision: Union[str, None] = '99e403f1531f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_reference',
    sa.Column('allergies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('medical_condition', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('food_intolerance', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dietary_preference', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_reference_id'), 'medical_reference', ['id'], unique=False)
    op.add_column('meal', sa.Column('ingredients', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('meal', sa.Column('image_bucketname', sa.String(), nullable=True))
    op.add_column('meal', sa.Column('image_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'image_filename')
    op.drop_column('meal', 'image_bucketname')
    op.drop_column('meal', 'ingredients')
    op.drop_index(op.f('ix_medical_reference_id'), table_name='medical_reference')
    op.drop_table('medical_reference')
    # ### end Alembic commands ###
