"""hh

Revision ID: 71685e90be61
Revises: 094f269d40fd
Create Date: 2024-11-09 17:42:40.927994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71685e90be61'
down_revision: Union[str, None] = '094f269d40fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_goal', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'health_goal', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_goal', type_='foreignkey')
    op.drop_column('health_goal', 'user_id')
    # ### end Alembic commands ###
