"""update last

Revision ID: da0f5f210612
Revises: 65872a3e7471
Create Date: 2024-11-09 20:30:48.957157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0f5f210612'
down_revision: Union[str, None] = '65872a3e7471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('calorie', sa.String(), nullable=True))
    op.add_column('user', sa.Column('bmr', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('active_factor', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_factor')
    op.drop_column('user', 'bmr')
    op.drop_column('user', 'calorie')
    # ### end Alembic commands ###
